### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by deestruct** [Harvey71/emdr#11]
Would you happen to have any thoughts on licensing for this repository?  Was your intention was to make it fully open source as a [Public Domain Dedication](https://choosealicense.com/licenses/unlicense/)?  Without a license being selected for it, the default becomes [No License](https://choosealicense.com/no-permission/) which means that "nobody else can copy, distribute, or modify your work".

**Comment by Harvey71** [comment]
I just added a MIT License file. Thank you for the hint.
