### ISSUE TITLE
Buzzers microcontroller replacement :)

### ISSUE THREAD

**Issue by deestruct** [Harvey71/emdr#12]
Replacing the Buzzers microcontroller similarly to how you did the Lightbar would be wonderful.  My wife uses it in her practice and her clients typically have opted for the Buzzers rather then the Lightbar, however having both Lightbar and Buzzers available would be great.  Current pricing for Teensy 4.0 units here are priced extremely high.

**Comment by Harvey71** [comment]
Hey, I just added new firmware sources and updated the documentation with microcontroller replacements for the buzzers. :-)

**Comment by deestruct** [comment]
Thank you!  Your efforts are greatly appreciated.
