### ISSUE TITLE
Wiring of lightbar. 

### ISSUE THREAD

**Issue by KaboomFox** [Harvey71/emdr#2]
I followed https://github.com/PaulStoffregen/WS2812Serial and connected pin 17 to 24 on the teensy board and have the data pin of the LED Strip to going to 17 VIN teensy pin but I was looking at your video in the comments you said you hooked up the data out of the led strip to the DAC pin of teensy. What is the correct Wiring of the Lightbar to Teensy?

**Comment by Harvey71** [comment]
Sorry, the comment in the video is incorrect. Connecting pin 24 and 17 is correct. But then you have to use the pin/connector "17 at Vin voltage" and connect it with Din on the light strip. "17 at Vin voltage" is exactly opposite to pin 26 and oddly has not a number on its own. I guess I mixed it up when ansering the comment in the video. I will clarify this in the video's comment as well as here. Thank you for the input.
