### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by deestruct** [Harvey71/emdr#9]
After struggling to get the setup to function from the tutorials, I was finally able to get it working using the final instructions provided by ooktown #3 which closed that issue. I am still awaiting some components to arrive so have not completed the fabricating the buzzers and lightbar hardware devices, but did get the RPi 4 and TFT 3.5" screen working now.

I am not getting audio though from the device on my headset connected to the 3.5mm jack when I test the sound via the GUI.  I can confirm that the audio is working in the RPi as when I connect to it via SSH and perform a basic audio test with the code `speaker-test -c2 -twav -l7`, I can hear the test functioning properly in my headset.  Immediately after the audio test is complete, I try the audio again using the GUI on the TFT screen and I cannot hear any sounds.

However, if I connect the RPi to my monitor using an HDMI cable and try testing the audio on the EMDR GUI I can hear the tones properly.

Can you please assist me in resolving this issue?  I am stumped why the only element not working in the audio output is the headphone jack via the EMDR GUI audio test.

**Comment by Harvey71** [comment]
Hi deestruct, please try to configure default audio output to jack. One way to do so is via command line:
`sudo amixer cset numid=3 1`

**Comment by deestruct** [comment]
I tried the suggested command via SSH and it did not work either.

**Comment by deestruct** [comment]
Perhaps I am doing something wrong in testing the audio via headphones.  Below are the steps I am performing to test the headphone jack for audible tones; I performed the steps below today after entering the command line you suggested and rebooting the system.

1) Press the EAR icon to enter the sound menu:
![20230704_192646](https://github.com/Harvey71/emdr/assets/138523438/f9ff045d-61c9-4af5-ba5d-b7670a84cb0a)

2) Try the vertical bar icon and then press the '?' to test the sound:
![20230704_192652](https://github.com/Harvey71/emdr/assets/138523438/fd7dc669-1d43-4f48-8eaa-e9f8b220d406)

3) Try the circular icon and then press the '?' to test the sound:
![20230704_192657](https://github.com/Harvey71/emdr/assets/138523438/19c024cd-477d-4152-93f4-f49144ea54d4)

**Comment by Harvey71** [comment]
I found something else in rhe PiBakery recipy that may help:

`echo "dtparam=audio=on"|cat - /boot/config.txt >/boot/config.tmp&&mv /boot/config.tmp /boot/config.txt`

You would have to execute this as root and do a reboot.

**Comment by deestruct** [comment]
I didn't initially execute that command as when I checked the config file it already had the following lines active:
![image](https://github.com/Harvey71/emdr/assets/138523438/1372fd0f-5f12-4a04-8551-92de0413614d)

I did execute the command though and it added the same line at the top of the config file as shown below:
![image](https://github.com/Harvey71/emdr/assets/138523438/630900d0-794a-42ec-8b1d-cfd227fad61f)

After rebooting, it still behaves the same.
